export const SET_TOP_MENU = 'SET_TOP_MENU'

export const SET_BANK_MENU = 'SET_BANK_MENU'

export const SET_RISK_MENU = 'SET_RISK_MENU'

export const SET_ACTIVE_TOP_INDEX = 'SET_ACTIVE_TOP_INDEX'

export const SET_ACTIVE_LEFT_INDEX = 'SET_ACTIVE_LEFT_INDEX'

export const SET_BANK_TYPE = 'SET_BANK_TYPE'

export const SET_ENTERPRISE_BASIC_INFO = 'SET_ENTERPRISE_BASIC_INFO'

export const SET_ENTERPRISE_MENUS = 'SET_ENTERPRISE_MENUS'